USE [master]
GO
/****** Object:  Database [lmao]    Script Date: 02/09/2017 11:29:18 a.m. ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'lmao')
BEGIN
CREATE DATABASE [lmao]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'lmao', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\lmao.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'lmao_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\lmao_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END

GO
ALTER DATABASE [lmao] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [lmao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [lmao] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [lmao] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [lmao] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [lmao] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [lmao] SET ARITHABORT OFF 
GO
ALTER DATABASE [lmao] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [lmao] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [lmao] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [lmao] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [lmao] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [lmao] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [lmao] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [lmao] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [lmao] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [lmao] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [lmao] SET  ENABLE_BROKER 
GO
ALTER DATABASE [lmao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [lmao] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [lmao] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [lmao] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [lmao] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [lmao] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [lmao] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [lmao] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [lmao] SET  MULTI_USER 
GO
ALTER DATABASE [lmao] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [lmao] SET DB_CHAINING OFF 
GO
ALTER DATABASE [lmao] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [lmao] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [lmao] SET  READ_WRITE 
GO
